# -*- coding: utf-8 -*-
"""FIN60003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1amZjOmdMaxvxyvIBK-Ihf-33-4Aq-s6R

Hypothesis Testing 2
"""

import pandas as pd

CSL_Data=pd.read_csv(r"/content/CSL.csv")
RHC_Data=pd.read_csv(r"/content/RHC.AX.csv")

CSL_Data.columns

RHC_Data.columns

CSL_Data=CSL_Data[["Return"]].dropna()
RHC_Data=RHC_Data[["Return"]].dropna()

from scipy import stats

T_test_value,p_value=stats.ttest_ind(a=CSL_Data.values,b=RHC_Data.values,equal_var=False)

print(p_value)

"""Hypothesis Testing 3"""

import pandas as pd

BHP_Data=pd.read_csv(r"/content/BHP.csv")
RIO_Data=pd.read_csv(r"/content/RIO.csv")

BHP_Data.columns

RIO_Data.columns

BHP_Data=BHP_Data[["Return"]].dropna()
RIO_Data=RIO_Data[["Return"]].dropna()

from scipy import stats

T_test_value,p_value=stats.ttest_ind(a=BHP_Data.values,b=RIO_Data.values,equal_var=False)

print(p_value)

print(T_test_value)

"""Linear Regression Using Python"""

y=BHP_Data.values
BHP_Data.shape

x=RIO_Data.values
RIO_Data.shape

from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x,y)

r_sq = model.score(x,y)
print('coefficient of determinention:',r_sq)
print('coefficient of corelation:',r_sq**0.5)
print('intercept:',model.intercept_)
print('slope:',model.coef_)

y_pred=model.predict(x)

import matplotlib.pyplot as plt
plt.scatter(x, y)
plt.plot(x, y_pred,color='black')
plt.show()